SHOW TABLES;
SHOW INDEX FROM ACCESS_LOG;

USE DB_STOCK;

-- ARTICLES		HOLDINGS	INTERESTS	PREDICTIONS		SECTORS		STOCKS		STOCKS_HISTORY		TRADE_HISTORY	USERS	ACCESS_LOG	SEARCH_LOG
SELECT * FROM ACCESS_LOG;

alter table ACCESS_LOG rename column ACCESS_ID to ACCESS_LOG_ID;