-- CREATE DATABASE DB_STOCK;


CREATE TABLE `ARTICLES` (
	`ARTICLE_ID`	BIGINT	NOT NULL	AUTO_INCREMENT	PRIMARY KEY	COMMENT 'AUTO_INCREMENT',
	`TITLE`	VARCHAR(255)	NULL,
	`RESPONSIBILITY`	FLOAT	NULL,
	`OPINION`	FLOAT	NULL	COMMENT '긍정부정',
	`REGISTRATION_DATE`	TIMESTAMP	NULL,
	`SECTORS_ID`	BIGINT	NOT NULL,
	`STOCK_ID`	BIGINT	NULL
);

CREATE TABLE `TRADE_HISTORY` (
	`TRADE_HISTORY_ID`	BIGINT	NOT NULL	AUTO_INCREMENT	PRIMARY KEY	COMMENT 'AUTO_INCREMENT',
	`TRADE_TYPE`	ENUM('BUY', 'SELL')	NULL,
	`TRANSACTION_AMOUNT`	FLOAT	NULL,
	`MARGIN_RATE`	FLOAT	NULL,
	`QUANTITY`	INT	NULL,
	`TRADE_DATE`	TIMESTAMP	NULL	DEFAULT CURRENT_TIMESTAMP,
	`HOLDING_ID`	BIGINT	NOT NULL
);

CREATE TABLE `USERS` (
	`USERS_ID`	BIGINT	NOT NULL	AUTO_INCREMENT	PRIMARY KEY	COMMENT 'AUTO_INCREMENT',
	`NAME`	VARCHAR(50)	NULL,
	`PASSWORD`	VARCHAR(500)	NULL,
	`BIRTHDATE`	TIMESTAMP	NULL,
	`EMAIL`	VARCHAR(100)	NULL	COMMENT '이메일이 아이디임'
);

CREATE TABLE `SECTORS` (
	`SECTORS_ID`	BIGINT	NOT NULL	AUTO_INCREMENT	PRIMARY KEY	COMMENT 'AUTO_INCREMENT',
	`NAME`	VARCHAR(20)	NULL
);

CREATE TABLE `STOCKS_HISTORY` (
	`STOCKS_HISTORY_ID`	BIGINT	NOT NULL	AUTO_INCREMENT	PRIMARY KEY	COMMENT 'AUTO_INCREMENT',
	`CLOSING_PRICE`	FLOAT	NULL,
	`PERFORMANCE`	FLOAT	NULL,
	`HISTORY_DATE`	TIMESTAMP	NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '인덱싱',
	`STOCK_ID`	BIGINT	NOT NULL
);

CREATE TABLE `INTERESTS` (
	`INTEREST_ID`	BIGINT	NOT NULL	AUTO_INCREMENT	PRIMARY KEY	COMMENT 'AUTO_INCREMENT',
	`LEVEL`	TINYINT	NOT NULL,
	`USERS_ID`	BIGINT	NOT NULL,
	`SECTORS_ID`	BIGINT	NOT NULL	COMMENT 'AUTO_INCREMENT'
);

CREATE TABLE `PREDICTIONS` (
	`PREDICTION_ID`	BIGINT	NOT NULL	AUTO_INCREMENT	PRIMARY KEY	COMMENT 'AUTO_INCREMENT',
	`PREDICTION_PRICE`	INT	NULL,
	`PREDICTION_DATE`	TIMESTAMP	NOT NULL,
	`CREATION_DATE`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '인덱싱',
	`STOCK_ID`	BIGINT	NULL,
	`SECTORS_ID`	BIGINT	NOT NULL
);

CREATE TABLE `STOCKS` (
	`STOCK_ID`	BIGINT	NOT NULL	AUTO_INCREMENT	PRIMARY KEY	COMMENT 'AUTO_INCREMENT',
	`NAME`	VARCHAR(50)	NULL,
	`SECTORS_ID`	BIGINT	NOT NULL
);

CREATE TABLE `HOLDINGS` (
	`HOLDING_ID`	BIGINT	NOT NULL	AUTO_INCREMENT	PRIMARY KEY	COMMENT 'AUTO_INCREMENT',
	`AVERAGE_PRICE`	FLOAT	NULL,
	`TOTAL_QUANTITY`	INT	NULL,
	`USERS_ID`	BIGINT	NOT NULL
);

CREATE TABLE `SEARCH_LOG` (
	`SEARCH_LOG_ID`	BIGINT	NOT NULL	AUTO_INCREMENT	PRIMARY KEY	COMMENT 'AUTO_INCREMENT',
	`USERS_ID`	BIGINT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`STOCK_ID`	BIGINT	NOT NULL	COMMENT 'AUTO_INCREMENT',
	`SEARCH_TIME`	TIMESTAMP	NOT NULL
);

CREATE TABLE `ACCESS_LOG` (
	`ACCESS_ID`	BIGINT	NOT NULL	AUTO_INCREMENT	PRIMARY KEY	COMMENT 'AUTO_INCREMENT',
	`USERS_ID`	BIGINT	NULL	COMMENT 'AUTO_INCREMENT',
	`SESSION_ID`	VARCHAR(100)	NOT NULL,
	`REFERER`	VARCHAR(500)	NULL,
	`ENTRY_PAGE`	VARCHAR(500)	NULL,
	`SOURCE_TYPE`	VARCHAR(30)	NOT NULL,
	`ACCESS_TIME`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
);



-- CONSTRAINT
ALTER TABLE `ARTICLES` ADD CONSTRAINT `FK_SECTORS_TO_ARTICLES_1` FOREIGN KEY (
	`SECTORS_ID`
)
REFERENCES `SECTORS` (
	`SECTORS_ID`
);

ALTER TABLE `ARTICLES` ADD CONSTRAINT `FK_STOCKS_TO_ARTICLES_1` FOREIGN KEY (
	`STOCK_ID`
)
REFERENCES `STOCKS` (
	`STOCK_ID`
);

ALTER TABLE `TRADE_HISTORY` ADD CONSTRAINT `FK_HOLDINGS_TO_TRADE_HISTORY_1` FOREIGN KEY (
	`HOLDING_ID`
)
REFERENCES `HOLDINGS` (
	`HOLDING_ID`
);

ALTER TABLE `STOCKS_HISTORY` ADD CONSTRAINT `FK_STOCKS_TO_STOCKS_HISTORY_1` FOREIGN KEY (
	`STOCK_ID`
)
REFERENCES `STOCKS` (
	`STOCK_ID`
);

ALTER TABLE `INTERESTS` ADD CONSTRAINT `FK_USERS_TO_INTERESTS_1` FOREIGN KEY (
	`USERS_ID`
)
REFERENCES `USERS` (
	`USERS_ID`
);

ALTER TABLE `INTERESTS` ADD CONSTRAINT `FK_SECTORS_TO_INTERESTS_1` FOREIGN KEY (
	`SECTORS_ID`
)
REFERENCES `SECTORS` (
	`SECTORS_ID`
);

ALTER TABLE `PREDICTIONS` ADD CONSTRAINT `FK_STOCKS_TO_PREDICTIONS_1` FOREIGN KEY (
	`STOCK_ID`
)
REFERENCES `STOCKS` (
	`STOCK_ID`
);

ALTER TABLE `PREDICTIONS` ADD CONSTRAINT `FK_SECTORS_TO_PREDICTIONS_1` FOREIGN KEY (
	`SECTORS_ID`
)
REFERENCES `SECTORS` (
	`SECTORS_ID`
);

ALTER TABLE `STOCKS` ADD CONSTRAINT `FK_SECTORS_TO_STOCKS_1` FOREIGN KEY (
	`SECTORS_ID`
)
REFERENCES `SECTORS` (
	`SECTORS_ID`
);

ALTER TABLE `HOLDINGS` ADD CONSTRAINT `FK_USERS_TO_HOLDINGS_1` FOREIGN KEY (
	`USERS_ID`
)
REFERENCES `USERS` (
	`USERS_ID`
);

ALTER TABLE `SEARCH_LOG` ADD CONSTRAINT `FK_USERS_TO_SEARCH_LOG_1` FOREIGN KEY (
	`USERS_ID`
)
REFERENCES `USERS` (
	`USERS_ID`
);

ALTER TABLE `SEARCH_LOG` ADD CONSTRAINT `FK_STOCKS_TO_SEARCH_LOG_1` FOREIGN KEY (
	`STOCK_ID`
)
REFERENCES `STOCKS` (
	`STOCK_ID`
);

ALTER TABLE `ACCESS_LOG` ADD CONSTRAINT `FK_USERS_TO_ACCESS_LOG_1` FOREIGN KEY (
	`USERS_ID`
)
REFERENCES `USERS` (
	`USERS_ID`
);

-- INDEX
CREATE INDEX IDX_STOCKS_HISTORY_STOCK_DATE ON `STOCKS_HISTORY` (`STOCK_ID`, `HISTORY_DATE`);
CREATE INDEX IDX_PREDICTIONS_STOCK_DATE ON `PREDICTIONS` (`STOCK_ID`, `PREDICTION_DATE`);

CREATE INDEX IDX_SEARCH_STOCK_TIME ON `SEARCH_LOG` (`STOCK_ID`, `SEARCH_TIME`);
CREATE INDEX IDX_SEARCH_USER ON `SEARCH_LOG` (`USERS_ID`);

CREATE INDEX IDX_ACCESS_TIME ON `ACCESS_LOG` (`ACCESS_TIME`);
CREATE INDEX IDX_ACCESS_SESSION ON `ACCESS_LOG` (`SESSION_ID`);